#!/usr/bin/env python3
"""Extract Slayer eligibility, original map item schedules and inventory rules."""
from pathlib import Path
import contextlib,json,hashlib
from extract_extended import tag_values
ROOT=Path(__file__).resolve().parents[2]
NAMES=['assault rifle','pistol','plasma pistol','plasma rifle','needler','shotgun','sniper rifle','rocket launcher','flamethrower']
def main():
 from reclaimer.meta.wrappers.halo1_map import Halo1Map
 out=ROOT/'halo64-assets/generated';cache=ROOT/'build/n64/assets/bloodgulch-decompressed.map'
 with (out/'pickup-extraction.log').open('w') as log,contextlib.redirect_stdout(log):
  h=Halo1Map();h.load_map(cache);es=h.tag_index.tag_index
  def get(path,kind):return tag_values(h.get_meta(next(i for i,e in enumerate(es) if e.path==path and e.class_1.enum_name==kind)))
  sc=tag_values(h.scnr_meta)
  def eligible(row):return any(row['type_'+str(i)] in ('slayer','all_games','all_games_except_ctf','all_games_except_ctf_and_race') for i in range(4))
  kinds={'weapons\\'+n+'\\'+n:i for i,n in enumerate(NAMES)}
  kinds.update({r'powerups\health pack':9,r'weapons\frag grenade\frag grenade':10,r'weapons\plasma grenade\plasma grenade':11,r'powerups\over shield':12,r'powerups\active camouflage':13})
  collections={e.path:get(e.path,'item_collection') for e in es if e.class_1.enum_name=='item_collection'}
  ammo=[]
  for n in NAMES:
   m=get('weapons\\'+n+'\\'+n,'weapon')['weap_attrs']['magazines'][0]
   loaded=min(m['rounds_total_initial'],m['rounds_loaded_maximum'])
   ammo.append([loaded,m['rounds_total_initial']-loaded,m['rounds_total_maximum']] if loaded else [100,0,0])
  spawnflags=[int(eligible(row)) for row in sc['player_starting_locations']]
  start=next(row for row in sc['starting_equipments'] if eligible(row));weapons=[]
  for i in range(1,6):
   path=start['item_collection_'+str(i)]
   if path:weapons.append(kinds[collections[path]['item_permutations'][0]['item']])
  weapons=(weapons+[-1,-1])[:2]
  grenades=[4,0] if not start['flags']['no_grenades'] else [0,0]
  if start['flags']['plasma_grenades']:grenades=[0,sum(grenades)]
  rows=[]
  for e in sc['netgame_equipments']:
   if not eligible(e):continue
   col=collections[e['item_collection']];perms=col['item_permutations'];assert 0<len(perms)<=2
   pos=e['position'];ks=[kinds[x['item']] for x in perms];weights=[round(x['weight']) for x in perms]
   rows.append(dict(pos=[pos['x']-68,pos['z'],-pos['y']-118],yaw=-e['facing'],period=e['spawn_time'] or col['spawn_time'] or 30,kind=(ks+[-1])[:2],first_weight=weights[0],total_weight=sum(weights)))
  camo=get(r'powerups\active camouflage','equipment')['eqip_attrs']['powerup_time']
 def f(x):return f'{x:.9e}f'
 lines=['/* Owned Xbox Blood Gulch tags; generated by extract_pickups.py. */','#include "pickup_rules.h"','const bg_ammo_rule bg_ammo_rules[9]={'+','.join('{'+','.join(map(str,r))+'}' for r in ammo)+'};', 'const uint8_t bg_slayer_spawns[]={'+','.join(map(str,spawnflags))+'};','const int bg_start_weapons[2]={'+','.join(map(str,weapons))+'};','const int bg_start_grenades[2]={'+','.join(map(str,grenades))+'};','const float bg_camo_duration='+f(camo)+';','const bg_map_item bg_map_items[]={']
 for r in rows:lines.append('{{'+','.join(map(f,r['pos']))+'},'+f(r['yaw'])+','+str(r['period'])+',{'+','.join(map(str,r['kind']))+'},'+str(r['first_weight'])+','+str(r['total_weight'])+'},')
 lines+=['};','const unsigned bg_map_item_count=sizeof(bg_map_items)/sizeof(bg_map_items[0]);']
 (out/'pickup_data.c').write_text('\n'.join(lines)+'\n')
 report=dict(cache_sha256=hashlib.sha256(cache.read_bytes()).hexdigest(),spawns=sc['player_starting_locations'],eligible_slayer_count=sum(spawnflags),starting_equipment=start,collections=collections,map_items=rows,ammo=ammo,camo_duration=camo,sources=['source/game/game_engine.c:game_engine_get_distance_rating_for_spawn,game_engine_update_item_spawn,game_engine_update_purge,handle_custom_starting_equipment','source/game/players.c:find_best_starting_location_index','source/items/weapons.c:weapon_handle_potential_inventory_item,weapon_new','source/units/units.c:unit_drop_inventory_weapons,unit_drop_grenades'])
 (out/'pickup-report.json').write_text(json.dumps(report,indent=2)+'\n')
 print('Extracted',sum(spawnflags),'Slayer spawns,',len(rows),'map placements; start',weapons,grenades)
if __name__=='__main__':main()
