#!/usr/bin/env python3
"""Bake pixel-aligned HUD quadrants from the locally extracted Xbox HUD bank."""
from pathlib import Path
import re
from PIL import Image, ImageOps

ROOT = Path(__file__).resolve().parents[2]


def main():
    source = (ROOT/'build/n64/generated/hud_data.c').read_text()
    images = re.findall(r'\{(hud_reticle_\w+),(\d+),(\d+),(\d+),(\d+),(\d+),(\d+)\}', source)
    assert len(images) == 12
    masks = []
    for index, (name, *dimensions) in enumerate(images):
        w, h, tw, th, ox, oy = map(int, dimensions)
        values = [int(v, 0) for v in re.search(r'\b'+name+r'\[\].*?=\{([^}]+)', source).group(1).split(',') if v.strip()]
        image = Image.new('L', (w, h))
        for y in range(th):
            for x in range(tw):
                image.putpixel((x+ox, y+oy), 255 if values[y*tw+x] & 1 else 0)
        size = 10 if index == 1 else 6 if index == 6 else 24
        image = image.resize((size, size), Image.Resampling.BOX)
        image = Image.blend(image, ImageOps.mirror(image), .5)
        if index not in (2, 9, 11):
            image = Image.blend(image, ImageOps.flip(image), .5)
        threshold = 48 if index in (5, 6, 7) else 72
        image = image.point(lambda a: 255 if a >= threshold else 0)
        mask = Image.new('L', (24, 24))
        mask.paste(image, ((24-size)//2, (24-size)//2))
        masks.append(mask)
    quadrants = [m.crop((0, 0, 12, 12)) for m in masks]
    quadrants += [masks[i].crop((0, 12, 12, 24)) for i in (2, 11, 9)]
    rows = [[sum(1 << (11-x) for x in range(12) if q.getpixel((x,y))) for y in range(12)] for q in quadrants]
    # Preserve recognizable source details thinner than one destination pixel.
    rows[7][11] |= 3  # Rocket's central range mark.
    for y in range(2, 6):
        rows[8][y] |= 1  # Warthog's connecting radial ticks.
    rows[8][11] |= 0x3c0
    # Scorpion's rectangular brackets, inward arrows and six side ticks.
    rows[10] = [0, 0, 0x01f, 0x190, 0x010, 0x010, 0x190, 0x010, 0x010, 0x190, 0x018, 0x01c]
    header = '''#ifndef BG_HUD_RETICLES_H
#define BG_HUD_RETICLES_H
/* Generated by pack_hud_reticles.py from the locally extracted Xbox bank.
 * Native 24x24 masks stored as 12x12 quadrants in the shared HUD atlas.
 * Mirror pairs are exact pixels, without fractional texture rescaling.
 * Plasma pistol, Ghost and Banshee retain distinct lower halves.
 * Pistol/sniper silhouettes occupy centered 10x10 / 6x6 footprints. */
static const uint16_t hud_reticle_quadrants[15][12]={
'''
    names = [i[0] for i in images]+['plasma_pistol_lower', 'banshee_lower', 'ghost_lower']
    for name, row in zip(names, rows):
        header += '    {'+','.join(f'0x{v:03x}' for v in row)+'}, /* '+name+' */\n'
    (ROOT/'port/n64/hud_reticles.h').write_text(header+'};\n#endif\n')


if __name__ == '__main__':
    main()
