#ifndef BG_WEAPON_EFFECTS_H
#define BG_WEAPON_EFFECTS_H
#include "game.h"
/* Owned tag values and sprites are generated by extract_weapon_effects.py. */
typedef struct {float radius,life;unsigned texture;uint8_t color[3];} bg_fx_definition;
extern const bg_fx_definition bg_fx_definitions[9];
extern const uint32_t bg_fx_textures[][256];
extern const unsigned bg_fx_texture_count,bg_fx_charge_texture,bg_fx_glow_texture,bg_fx_trail_texture;
extern const float bg_fx_world_markers[9][2][3];
extern const uint16_t bg_fx_marker_offsets[9][4];
extern const int16_t bg_fx_marker_poses[][2][3];
#define BG_FX_TRAILS 4
#define BG_FX_TRAIL_LIFE 1.25f
typedef struct {float start[3],end[3],muzzle[3],age;bool active;} bg_fx_trail;
typedef struct {float age;int weapon;unsigned sequence;bool charged;} bg_fx_shot;
extern bg_fx_shot bg_fx_shots[4];
extern bg_fx_trail bg_fx_trails[BG_FX_TRAILS];
typedef struct {float origin[3],age;int vehicle,kind;} bg_fx_vehicle_burst;
extern bg_fx_vehicle_burst bg_fx_vehicle_bursts[4];
void bg_fx_reset(void);
void bg_fx_update(float dt);
float bg_fx_flash(unsigned player);
float bg_fx_charge(unsigned player);
#endif
